# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/lab/4B_Research/SS_DDP/OPC_test/Enable_Flag/Enable_Flag/Enable_Flag.srcs/sources_1/ip/CMEM/CMEM.xci
# IP: The module: 'CMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab/4B_Research/SS_DDP/OPC_test/Enable_Flag/Enable_Flag/Enable_Flag.gen/sources_1/ip/CMEM/CMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CMEM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/lab/4B_Research/SS_DDP/OPC_test/Enable_Flag/Enable_Flag/Enable_Flag.srcs/sources_1/ip/CMEM/CMEM.xci
# IP: The module: 'CMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab/4B_Research/SS_DDP/OPC_test/Enable_Flag/Enable_Flag/Enable_Flag.gen/sources_1/ip/CMEM/CMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CMEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
