# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/lab/4B_Research/Matuzaka/DDP_FIR_32bit/Matuzaka_DDP_32bit.srcs/sources_1/ip/B_SubPS/B_SubPS.xci
# IP: The module: 'B_SubPS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab/4B_Research/Matuzaka/DDP_FIR_32bit/Matuzaka_DDP_32bit.gen/sources_1/ip/B_SubPS/B_SubPS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_SubPS'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/lab/4B_Research/Matuzaka/DDP_FIR_32bit/Matuzaka_DDP_32bit.srcs/sources_1/ip/B_SubPS/B_SubPS.xci
# IP: The module: 'B_SubPS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab/4B_Research/Matuzaka/DDP_FIR_32bit/Matuzaka_DDP_32bit.gen/sources_1/ip/B_SubPS/B_SubPS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_SubPS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
