# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/lab/4B_Research/FIR_DDP/Masa_FIR_DDP_16bit/MASA_FIR_DDP_16bit/MASA_FIR_DDP_16bit.srcs/sources_1/ip/DMEM/DMEM.xci
# IP: The module: 'DMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab/4B_Research/FIR_DDP/Masa_FIR_DDP_16bit/MASA_FIR_DDP_16bit/MASA_FIR_DDP_16bit.gen/sources_1/ip/DMEM/DMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMEM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/lab/4B_Research/FIR_DDP/Masa_FIR_DDP_16bit/MASA_FIR_DDP_16bit/MASA_FIR_DDP_16bit.srcs/sources_1/ip/DMEM/DMEM.xci
# IP: The module: 'DMEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab/4B_Research/FIR_DDP/Masa_FIR_DDP_16bit/MASA_FIR_DDP_16bit/MASA_FIR_DDP_16bit.gen/sources_1/ip/DMEM/DMEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
