# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/lab/4B_Research/FIR_DDP/Masa_FIR_DDP_16bit/XDC/.xdc

# IP: ip/PS_1/PS.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS || ORIG_REF_NAME==PS} -quiet] -quiet
